### ISSUE TITLE
Import component into `.mdx` file?

### ISSUE THREAD

**Issue by callumflack** [freekrai/remix-docs#1]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Import a component form the `app/components` directory into an `.mdx` file.

### Expected Behavior

Import and render a component.

### Actual Behavior

It renders a text string, not an imported component.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/749885/192214998-09522a92-1d6a-4436-a4ba-379ec3bb010d.png">

**Comment by callumflack** [comment]
@freekrai this is really nice template, thank you. Kind of standardises a number of approaches, love the option between remote versus local. I am genuinely confused about the component import though.

**Comment by freekrai** [comment]
This uses Stripe’s [Markdoc](https://markdoc.dev)  for rendering so it’s a tad different.

You’d have to add components via [https://github.com/freekrai/remix-docs/blob/main/app/components/Markdown.tsx](https://github.com/freekrai/remix-docs/blob/main/app/components/Markdown.tsx) and [https://github.com/freekrai/remix-docs/blob/main/app/utils/markdoc.server.ts](https://github.com/freekrai/remix-docs/blob/main/app/utils/markdoc.server.ts)

**Comment by freekrai** [comment]
I'm working on some docs around this stack which will include a section on markdoc and adding more components.

**Comment by callumflack** [comment]
Ah yes, my bad. Thanks 🙏🏻

**Comment by callumflack** [comment]
MarkDoc docs are solid, might only need a quick overview of it.

**Comment by freekrai** [comment]
Yeah markDoc is nice
